---
abstract: 'Yet Another Path Router for HTTP'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::MockObject: 0
  Test::More: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Router
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  Hash::Merge: 0
  Lingua::EN::Inflect::Number: 0
  List::MoreUtils: 0
  Mouse: 0.14
  String::CamelCase: 0
  Text::SimpleTable: 0
  URI::Template::Restrict: 0
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
